name: network_quality_statistic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  mapbox_gl: ^0.16.0
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  image_picker: ^1.0.2
  path_provider: ^2.1.0
  local_auth: ^2.1.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/data/

